# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Global Public Key
  SSH_PUBLIC_KEY = File.readlines("/home/yyasar/.ssh/id_rsa.pub").first.strip
  $COMMON_POST_INSTALL = <<-SCRIPT
      echo #{SSH_PUBLIC_KEY} >> /home/vagrant/.ssh/authorized_keys
      apt update
      apt install vim -y
      apt install parted -y
      parted /dev/sdb mklabel msdos
      parted /dev/sdb mkpart primary 512 100%
      mkfs.ext4 /dev/sdb1
      mkdir -p /opt/data
      echo `blkid /dev/sdb1 | awk '{print$2}' | sed -e 's/"//g'` /opt/data  ext4   noatime,nobarrier   0   0 >> /etc/fstab
      mount -a
  SCRIPT
  $DOCKER_POST_INSTALL = <<-SCRIPT
      systemctl stop docker
      #tee -a /etc/docker/daemon.json > /dev/null <<EOT
      #  {
      #    "data-root": "/opt/data/"
      #  }
      #EOT
      systemctl restart docker
  SCRIPT

  config.vm.define "master-server", primary: true do |master|
    master.vm.box = "debian/bullseye64"
    master.vm.hostname = "master"
    master.vm.network "public_network", ip: "192.168.1.50", bridge: "enp2s0", hostname: true
    master.vm.disk :disk, size: "50GB", name: "docker_data_disk"

    master.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "8192"]
      vb.customize ["modifyvm", :id, "--cpus", "4"]
    end

    master.vm.provision "shell", inline: $COMMON_POST_INSTALL
    master.vm.provision "shell", path: "https://releases.rancher.com/install-docker/20.10.sh"
    master.vm.provision "shell", inline: $DOCKER_POST_INSTALL
  end

  config.vm.define "slave-server1" do |slave1|
    #slave1.vm.box = "debian/bullseye64"
    slave1.vm.box = "generic/debian10"
    slave1.vm.hostname = "slave1"
    slave1.vm.network "public_network", ip: "192.168.1.51", bridge: "enp2s0", hostname: true
    slave1.vm.disk :disk, size: "50GB", name: "docker_data_disk"

    slave1.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "2048"]
      vb.customize ["modifyvm", :id, "--cpus", "2"]
    end

    slave1.vm.provision "shell", inline: $COMMON_POST_INSTALL
    slave1.vm.provision "shell", path: "https://releases.rancher.com/install-docker/20.10.sh"
    slave1.vm.provision "shell", inline: $DOCKER_POST_INSTALL
  end
end